apiVersion: v1
kind: Secret

metadata:
  name: django-secret
  namespace: devsu-demo

type: Opaque

stringData:
  DJANGO_SECRET_KEY: "change-me"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "devsu-demo.local,localhost,127.0.0.1"
  DATABASE_NAME: "db.sqlite3"
